# You can use this to store API keys, mail server settings,
# or any other kind of configuration data that your application needs.
# In order to keep your production settings secret, store the production
# copy of this file on your server under shared/config/config.yml and copy
# it on deployment with this Capistrano task:#

# task :copy_config_files do
#   filename = "config/config.yml"
#   run "cp #{shared_path}/#{filename} #{release_path}/#{filename}"
# end
# after "deploy:update_code", :copy_config_files

encryption_key: 312edbe0ac1e3060356e3b65979486979ae247869c908555373e0fb0fe17213b0e9ad7005aabd8ddf2345d474c48f548f694668245ac9f2874088ca75b960f50

mailer:
  server: mail.example.com
  username: someLOGIN
  password: s0meth1ngs3cr3t
paypal:
  ip:         212.168.2.2
  login:      sqwomeLOGIN.yahoo.com
  password:   soqwemePASSWORD
  signature:  someqweSIGNATURE
authnet:
  login:      sdfsdf
  password:   sdfsdfsdf
vat: false
require_state_in_address: true

# tax_per_state_id is a field for tax being applied at the state level or country wide level in "TaxRate model"
tax_per_state_id: true

paperclip:
  s3_protocol: https
  s3_credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  path: ':class/:attachment/:style/:hash.:extension'
  bucket: <%= ENV['FOG_DIRECTORY'] %>
  hash_secret: f8c07cf79094ec06f77b6024b5d7936c79b5227274fb8e82c00blaha